 create table usuario (id bigint generated by default as identity, account_expired boolean not null, account_locked boolean not null, active boolean not null, credentials_expired boolean not null, password varchar(255), roles varchar(255), username varchar(255), primary key (id));
 create table cliente (cpf varchar(255), data_nascimento date, nome varchar(255), status varchar(255), id bigint not null, primary key (id));
 create table conta (numero bigint generated by default as identity, saldo numeric(19,2), cliente_id bigint, primary key (numero));
 alter table cliente add constraint UK_r1u8010d60num5vc8fp0q1j2a unique (cpf);
 alter table usuario add constraint UK_863n1y3x0jalatoir4325ehal unique (username);
 alter table cliente add constraint FKsitxst8o302fspskxfjatuyrl foreign key (id) references usuario;
 alter table conta add constraint FKfksaesgpmec0cph81iq5or1wn foreign key (cliente_id) references cliente;
 create table hibernate_sequences (sequence_name varchar(255) not null, next_val bigint, primary key (sequence_name));
 insert into hibernate_sequences(sequence_name, next_val) values ('default', 3);
